"""empty message

Revision ID: 23582967fb52
Revises: 33865a3527d7
Create Date: 2017-03-07 05:04:49.095009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23582967fb52'
down_revision = '33865a3527d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
